# Generated by Django 4.2.11 on 2024-06-15 19:37

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('code', models.SlugField(help_text='Уникальный идентификатор из латинских символов', max_length=30, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=60, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Описание')),
            ],
            options={
                'db_table': 'payment_status',
                'ordering': ('title',),
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный генерируемый идентификатор')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Электронный кошелёк',
                'verbose_name_plural': 'Электронные кошельки',
                'db_table': 'wallet',
                'ordering': ('-user__date_joined',),
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('type', models.CharField(choices=[('income', 'Пополнение'), ('outcome', 'Списание'), ('payment', 'Оплата'), ('reserving', 'Резервирование')], max_length=20, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet', verbose_name='Кошелек')),
            ],
            options={
                'verbose_name': 'Транзакция виртуального счета',
                'verbose_name_plural': 'Транзакции виртуального счета',
                'db_table': 'wallet_transaction',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WalletStatus',
            fields=[
                ('code', models.SlugField(help_text='Уникальный идентификатор из латинских символов', max_length=30, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=60, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус электронного кошелька',
                'verbose_name_plural': 'Статусы электронного кошелька',
                'db_table': 'wallet_status',
                'ordering': ('title',),
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='walletstatus_title_idx')],
            },
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.ForeignKey(db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets_from_status', to='payments.walletstatus', verbose_name='Статус'),
        ),
    ]
