# Generated by Django 4.2.13 on 2025-09-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
