# Model values
MAX_PRICE_DIGITS = 10

MIN_LESSON_COST_RUB = 0

# Memory sizes
FILE_EXTENSION_STR = 'svg'
KB_IN_MB = 1024
BYTE_IN_KB = 1024

ONE_MB = KB_IN_MB * BYTE_IN_KB
ONE_KB = BYTE_IN_KB
ONE_BYTE = 1

SVG_LIMIT_MB = 3
MAX_SVG_SIZE = ONE_MB * SVG_LIMIT_MB

# Visibility sizes
REQUIRED_WIDTH_PX = 400
REQUIRED_HEIGTH_PX = 200
