# Generated by Django 4.2.11 on 2024-06-15 19:37

import django.core.validators
from django.db import migrations, models
import rates.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('code', models.SlugField(help_text='Уникальный идентификатор из латинских символов', max_length=30, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('lesson_cost', models.DecimalField(decimal_places=2, help_text='Стоимость одного занятия в рамках тарифа', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость занятия')),
                ('theme_image', models.FileField(help_text='Стилевое изображение тарифа в формате SVG с размером 400 на 200 пикселей', upload_to='rates/themes/svgs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg']), rates.validators.svg_size_validator, rates.validators.svg_file_size_validator], verbose_name='Стилевая тема')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'rate',
                'ordering': ['lesson_cost'],
                'indexes': [models.Index(fields=['code'], name='rate_code_idx')],
            },
        ),
    ]
