# Generated by Django 4.2.13 on 2025-09-03 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': ('Пользователь с таким номером телефона уже зарегистрирован!',)}, help_text='в формате +7(XXX)XXXXXXX или 8(XXX)XXXXXXX', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Номер телефона должен быть в формате +7(XXX)XXXXXXX или 8(XXX)XXXXXXX', regex='^(8|\\+7)\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
