# Generated by Django 4.2.11 on 2024-06-15 19:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название новости не более 256 символов', max_length=256, unique_for_date='created_at', validators=[core.validators.starts_with_uppercase], verbose_name='Название')),
                ('text', models.TextField(unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PUB', 'Опубликовано')], default='DF', max_length=15, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время обновления', verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ('-created_at', 'title'),
            },
        ),
    ]
