# Generated by Django 4.2.11 on 2024-06-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rates', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='studentrateassignment',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.rate', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='studentrateassignment',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile', verbose_name='Профиль преподавателя'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rates',
            field=models.ManyToManyField(blank=True, related_name='student_rate_profiles', through='profiles.StudentRateAssignment', to='rates.rate', verbose_name='Тарифы'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='teacherrateassignment',
            index=models.Index(fields=['rate'], name='teacher_rate_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherrateassignment',
            index=models.Index(fields=['teacher_profile'], name='teacher_p_rate_assignment_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherrateassignment',
            unique_together={('rate', 'teacher_profile')},
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['telegram_username'], name='telegram_username_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrateassignment',
            index=models.Index(fields=['rate'], name='student_rate_assignment_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrateassignment',
            index=models.Index(fields=['student_profile'], name='student_p_rate_assignment_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentrateassignment',
            unique_together={('rate', 'student_profile')},
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['telegram_username'], name='telegram_username_index'),
        ),
    ]
