GENERATE_ID_FIELD_LENGTH = 5
TITLE_FIELD_LENGTH = 200

MAX_PRICE_DIGITS = 10

FILE_EXTENSIONS_STR = ('png', 'jpeg', 'jpg')

REQUIRED_WIDTH_PX = 1000
REQUIRED_HEIGTH_PX = 750


KB_IN_MB = 1024
BYTE_IN_KB = 1024

ONE_MB = KB_IN_MB * BYTE_IN_KB
ONE_KB = BYTE_IN_KB
ONE_BYTE = 1

IMAGE_LIMIT_MB = 8
MAX_IMAGE_SIZE = ONE_MB * IMAGE_LIMIT_MB
