# Constants:
DAYS_IN_YEAR = 365

MIN_VALID_AGE = 3
MAX_VALID_AGE = 120
ADULT_AGE_THRESHOLD = 18
ADULT_AVG_AGE = 16

PRIMARY_KEY_CODE_LENGHT = 30
SMALL_FIELD_LENGTH = 60
MEDIUM_FIELD_LENGTH = 100
BIG_FIELD_LENGTH = 150

DEFAULT_DECIMAL_PLACES = 2

SMALL_DESCRIPTION_FIELD_LENGTH = 500
MEDIUM_DESCRIPTION_FIELD_LENGTH = 1000
BIG_DESCRIPTION_FIELD_LENGTH = 2000

DEFAULT_EXTRA_FIELD_COUNT = 1

MAX_PHONE_LENGTH = 15
MAX_TELEGRAM_USERNAME_LENGTH = 32

EDUCATION_CODE_LENGTH = 3
GENDER_CODE_LENGTH = 1


# Messages, errors, etc.:
USER_ERROR_MESSAGES = {
    'USERNAME_UNIQUE_ERROR': 'Такой логин уже занят другим пользователем!',
    'EMAIL_UNIQUE_ERROR': 'Пользователь с таким email уже зарегистрирован!',
    'PHONE_UNIQUE_ERROR': (
        'Пользователь с таким номером телефона уже зарегистрирован!',
    )
}
