# Generated by Django 4.2.11 on 2024-06-15 19:37

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import lessons.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('code', models.SlugField(help_text='Уникальный идентификатор из латинских символов', max_length=30, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=60, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус занятия',
                'verbose_name_plural': 'Статусы занятия',
                'db_table': 'lesson_status',
                'ordering': ('title',),
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='lessonstatus_title_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания занятия', verbose_name='Время создания')),
                ('started_from', models.DateTimeField(help_text='Дата и время начала занятия', validators=[lessons.validators.validate_time_interval], verbose_name='Время начала')),
                ('finished_to', models.DateTimeField(blank=True, help_text='Дата и время конца занятия.\nОставьте пустым, если занятие длится не более 1 часа', validators=[lessons.validators.validate_time_interval], verbose_name='Время окончания')),
                ('rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_from_rate', to='rates.rate', verbose_name='Тариф')),
                ('status', models.ForeignKey(db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_from_status', to='lessons.lessonstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'lesson',
                'ordering': ('-started_from',),
            },
        ),
    ]
