# Generated by Django 4.2.11 on 2024-06-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_with_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.PROTECT, related_name='lessons_with_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['started_from'], name='lesson_start_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['finished_to'], name='lesson_finish_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher'], name='lesson_teacher_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student'], name='lesson_student_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['rate'], name='lesson_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lesson_status_idx'),
        ),
    ]
