# Generated by Django 4.2.11 on 2024-06-15 19:37

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заказа', verbose_name='Время создания заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('code', models.SlugField(help_text='Уникальный идентификатор из латинских символов', max_length=30, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=60, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, unique=True, validators=[core.validators.starts_with_uppercase], verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
                'db_table': 'order_status',
                'ordering': ('title',),
                'abstract': False,
                'indexes': [models.Index(fields=['title'], name='orderstatus_title_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_from_order', to='orders.order', verbose_name='Заказ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_from_services', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга заказа',
                'verbose_name_plural': 'Услуги заказа',
                'db_table': 'order_services',
                'ordering': ('-service',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders_from_service', through='orders.OrderService', to='services.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='status_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_from_status', to='orders.orderstatus', verbose_name='Статус'),
        ),
    ]
