# Generated by Django 4.2.11 on 2024-06-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['order'], name='order_services_idx'),
        ),
        migrations.AddIndex(
            model_name='orderservice',
            index=models.Index(fields=['service'], name='service_orders_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderservice',
            unique_together={('order', 'service')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_user_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
    ]
